#---------------------------------------------------------------------------
# Python:
#

# Using the jedi autocompletion library
# [[plugins]]
# repo = 'davidhalter/jedi-vim'
# if = "!has('nvim')"
# if = "!has('python3')"
# on_ft = 'python'

## Pyflakes, Pep8 and mccabe code complexity checker
# [[plugins]]
# repo = "andviro/flake8-vim"
# on_ft = 'python'
# hook_source = '''
#   let g:PyFlakeOnWrite = 1
#   let g:PyFlakeCheckers = 'pep8'
# '''

## A nicer Python indentation style
[[plugins]]
repo = "hynek/vim-python-pep8-indent"¬
on_ft = 'python'

# Activate the versions and the virtualenvs of pyenv within a live VIM session
[[plugins]]
repo = 'lambdalisue/vim-pyenv'
on_ft = 'python'

# deoplete.nvim source for Python
[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = 'python'
if = 'has("nvim")'

#---------------------------------------------------------------------------
# PHP:
#

# Padawan.php source for deoplete.
# [[plugins]]
# repo = 'pbogut/deoplete-padawan'
# on_ft = 'php'
# if = 'has("nvim")'

# This script allows you to indent HTML sections in PHP files
[[plugins]]
repo = 'captbaritone/better-indent-support-for-php-with-html'
on_ft = 'php'

# Padawan.php source for deoplete.
[[plugins]]
repo = 'pbogut/deoplete-padawan'
on_ft = 'php'

#---------------------------------------------------------------------------
# Java:
#

# Updated javacomplete plugin for vim.
[[plugins]]
repo = 'artur-shaik/vim-javacomplete2'
on_ft = 'java'

#---------------------------------------------------------------------------
# HTML5+CSS3:
#

# HTML5 omnicomplete and syntax
[[plugins]]
repo = 'othree/html5.vim'
on_ft = 'html'

# Add CSS3 syntax support
[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = 'css'

# Preview colours in source code
[[plugins]]
repo = 'ap/vim-css-color'

# emmet for vim
[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'css', 'javascript', 'php']

# Auto close (X)HTML tags
[[plugins]]
repo = 'alvan/vim-closetag'

# A Vim plugin that always highlights the enclosing html/xml tags
[[plugins]]
repo = 'valloric/matchtagalways'
on_ft = ['html', 'xml']

#---------------------------------------------------------------------------
# Javascript:
#

# Enhanced javascript syntax file
[[plugins]]
repo = 'jelera/vim-javascript-syntax'
on_ft = 'javascript'

# A vim javascript indent script
[[plugins]]
repo = 'jiangmiao/simple-javascript-indenter'
on_ft = 'javascript'

# Tern plugin for Vim
[[plugins]]
repo = 'marijnh/tern_for_vim'
on_ft = 'javascript'
build = 'npm install'

# deoplete.nvim source for javascript
[[plugins]]
repo = 'carlitux/deoplete-ternjs'
on_ft = 'javascript'
if = 'has("nvim")'
build = 'npm install -g tern'

# deoplete.nvim source for javascript
[[plugins]]
repo = 'mhartington/deoplete-typescript'
on_ft = 'javascript'
if = 'has("nvim")'
build = 'npm -g install typescript'

# React JSX syntax highlighting and indenting for vim.
[[plugins]]
repo = 'mxw/vim-jsx'

# Syntax Highligth for Vue.js components
[[plugins]]
repo = 'posva/vim-vue'

# Generate JSDoc to your JavaScript code.
[[plugins]]
repo = 'heavenshell/vim-jsdoc'
on_ft = 'javascript'

# Tools and environment to make Vim superb for developing with Node.js. Like Rails.vim for Node.
[[plugins]]
repo = 'moll/vim-node'
on_ft = 'javascript'

#---------------------------------------------------------------------------
# YAML:
#

# Add additional support for Ansible in VIM
[[plugins]]
repo = 'chase/vim-ansible-yaml'

#---------------------------------------------------------------------------
# Markdown:
#

#---------------------------------------------------------------------------
# Json:
#

# A better JSON for Vim: distinct highlighting of keywords vs values, JSON-specific (non-JS) warnings, quote concealing. Pathogen-friendly.
[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'

#---------------------------------------------------------------------------
# Toml:
#

# Vim syntax for TOML.
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml', 'conf']

#---------------------------------------------------------------------------
# UML:
#

# vim syntax file for plantuml
[[plugins]]
repo = 'aklt/plantuml-syntax'
on_ft = 'plantuml'

# Inline previews for Plantuml sequence diagrams. OMG!
[[plugins]]
repo = 'scrooloose/vim-slumlord'
on_ft = 'plantuml'

#---------------------------------------------------------------------------
# LaTex:
#

# A modern vim plugin for editing LaTeX files.
[[plugins]]
repo = 'lervag/vimtex'
on_ft = ['tex', 'plaintex']
