# Dark powered Vim/Neovim plugin manager
[[plugins]]
repo = 'Shougo/dein.vim'

# Vim syntax for TOML.
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

# Dark powered asynchronous unite all interfaces for neovim
# [[plugins]]
# repo = 'Shougo/denite.nvim'
# if = 'has("nvim")'

# Unite and create user interfaces
[[plugins]]
repo = 'Shougo/unite.vim'

# Powerful file explorer implemented by Vim script
[[plugins]]
repo = 'Shougo/vimfiler.vim'
depends = 'unite.vim'

# Run commands quickly.
[[plugins]]
repo = 'thinca/vim-quickrun'

# A tree explorer
[[plugins]]
repo = 'scrooloose/nerdtree'

# NERDTree and tabs together
[[plugins]]
repo = 'jistr/vim-nerdtree-tabs'

# Extra syntax and highlight for nerdtree files
[[plugins]]
repo = 'tiagofumo/vim-nerdtree-syntax-highlight'

# A plugin of NERDTree showing git status
# [[plugins]]
# repo = 'Xuyuanp/nerdtree-git-plugin'

# A light and configurable statusline
[[plugins]]
repo = 'itchyny/lightline.vim'

# Displaying the indention levels with thin vertical lines
[[plugins]]
repo = 'Yggdroot/indentLine'

# File-type sensible comments
[[plugins]]
repo = 'tomtom/tcomment_vim'

# Highlights trailing whitespace in red and provides :FixWhitespace to fix it.
[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

# Handles bracketed-paste-mode
[[plugins]]
repo = 'ConradIrwin/vim-bracketed-paste'

# Delete/change/add parentheses/quotes/XML-tags/much more with ease
[[plugins]]
repo = 'tpope/vim-surround'

# The standard snippets repository for neosnippet
[[plugins]]
repo = 'Shougo/neosnippet-snippets'

# Syntax checking hacks
# [[plugins]]
# repo = 'scrooloose/syntastic'

# Asynchronous Lint Engine
[[plugins]]
repo = 'w0rp/ale'

# Insert several candidates with a single key
[[plugins]]
repo = 'kana/vim-smartchr'
on_i = 1

# Open URI with your favorite browser
[[plugins]]
repo = 'tyru/open-browser.vim'

# Search Dash.app [\d]
[[plugins]]
repo = 'rizzatti/dash.vim'

# Simple templates plugin
[[plugins]]
repo = 'aperezdc/vim-template'

# Generate a beautiful color swatch of the current color scheme
[[plugins]]
repo = 'cocopon/colorswatch.vim'

# Adds filetype glyphs (icons) to other plugins such as NERDTree, lightline.vim
[[plugins]]
repo = 'ryanoasis/vim-devicons'

# search status
[[plugins]]
repo = 'osyo-manga/vim-anzu'

# Git wrapper
[[plugins]]
repo = 'tpope/vim-fugitive'

# edit evernote on vim.
# [[plugins]]
# repo = 'kakkyz81/evervim'

# Changes the splash of Vim as you like.
[[plugins]]
repo = 'thinca/vim-splash'

# The interactive scratchpad for hackers.
[[plugins]]
repo = 'metakirby5/codi.vim'

# Context filetype library for Vim script
[[plugins]]
repo = "Shougo/context_filetype.vim"

# Web-enhanced Extensible Neovim Frontend
[[plugins]]
repo = 'rhysd/nyaovim-popup-tooltip'

# Vim plugin that displays tags in a window, ordered by scope
[[plugins]]
repo = 'majutsushi/tagbar'

# responsive tabline
[[plugins]]
repo = 'yami-beta/vim-responsive-tabline'

# Brings physics-based smooth scrolling to the Vim world!
[[plugins]]
repo = 'yuttie/comfortable-motion.vim'

# Vim plugin to dim inactive windows
[[plugins]]
repo = 'blueyed/vim-diminactive'

# Insert or delete brackets, parens, quotes in pair
[[plugins]]
repo = 'jiangmiao/auto-pairs'

# Plugin to toggle, display and navigate marks
# [[plugins]]
# repo = 'kshenoy/vim-signature'

# Underlines the word under the cursor
[[plugins]]
repo = 'itchyny/vim-cursorword'

# Vim motions on speed!
[[plugins]]
repo = 'easymotion/vim-easymotion'

# Deoplete source for emoji codes
[[plugins]]
repo = 'fszymanski/deoplete-emoji'

# Syntax source for neocomplete/deoplete/ncm
[[plugins]]
repo = 'Shougo/neco-syntax'

#---------------------------------------------------------------------------
# ColorScheme:
#

# Material theme for vim
# [[plugins]]
# repo = 'jdkanani/vim-material-theme'

# A vim theme inspired by Atom's default dark theme
# [[plugins]]
# repo = 'gosukiwi/vim-atom-dark'

# Monokai color scheme for Vim converted from Textmate theme
# [[plugins]]
# repo = 'sickill/vim-monokai'

# A 24bit colorscheme for Vim, Airline and Lightline
[[plugins]]
repo = 'jacoborus/tender'

# Oceanic Next theme for neovim
[[plugins]]
repo = 'mhartington/oceanic-next'

#---------------------------------------------------------------------------
# Python:
#

# Using the jedi autocompletion library
# [[plugins]]
# repo = 'davidhalter/jedi-vim'
# if = "!has('nvim')"
# if = "!has('python3')"
# on_ft = 'python'

## Pyflakes, Pep8 and mccabe code complexity checker
# [[plugins]]
# repo = "andviro/flake8-vim"
# on_ft = 'python'
# hook_source = '''
#   let g:PyFlakeOnWrite = 1
#   let g:PyFlakeCheckers = 'pep8'
# '''

## A nicer Python indentation style
[[plugins]]
repo = "hynek/vim-python-pep8-indent"¬
on_ft = 'python'

# Activate the versions and the virtualenvs of pyenv within a live VIM session
[[plugins]]
repo = 'lambdalisue/vim-pyenv'
on_ft = 'python'

# deoplete.nvim source for Python
[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = 'python'
if = 'has("nvim")'

#---------------------------------------------------------------------------
# PHP:
#

# Padawan.php source for deoplete.
# [[plugins]]
# repo = 'pbogut/deoplete-padawan'
# on_ft = 'php'
# if = 'has("nvim")'

# This script allows you to indent HTML sections in PHP files
[[plugins]]
repo = 'captbaritone/better-indent-support-for-php-with-html'
on_ft = 'php'

# Padawan.php source for deoplete.
[[plugins]]
repo = 'pbogut/deoplete-padawan'
on_ft = 'php'

#---------------------------------------------------------------------------
# Java:
#

# Updated javacomplete plugin for vim.
[[plugins]]
repo = 'artur-shaik/vim-javacomplete2'
on_ft = 'java'

#---------------------------------------------------------------------------
# HTML5+CSS3:
#

# HTML5 omnicomplete and syntax
[[plugins]]
repo = 'othree/html5.vim'
on_ft = 'html'

# Add CSS3 syntax support
[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = 'css'

# Preview colours in source code
[[plugins]]
repo = 'ap/vim-css-color'

# emmet for vim
[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'css', 'javascript', 'php']

# Auto close (X)HTML tags
[[plugins]]
repo = 'alvan/vim-closetag'

# A Vim plugin that always highlights the enclosing html/xml tags
[[plugins]]
repo = 'valloric/matchtagalways'
on_ft = ['html', 'xml']

#---------------------------------------------------------------------------
# Javascript:
#

# Enhanced javascript syntax file
[[plugins]]
repo = 'jelera/vim-javascript-syntax'
on_ft = 'javascript'

# A vim javascript indent script
[[plugins]]
repo = 'jiangmiao/simple-javascript-indenter'
on_ft = 'javascript'

# Tern plugin for Vim
# [[plugins]]
# repo = 'marijnh/tern_for_vim'
# on_ft = 'javascript'
# build = 'npm install'

# deoplete.nvim source for javascript
[[plugins]]
repo = 'carlitux/deoplete-ternjs'
on_ft = 'javascript'
if = 'has("nvim")'
build = 'npm install -g tern'

# deoplete.nvim source for javascript
[[plugins]]
repo = 'mhartington/deoplete-typescript'
on_ft = 'javascript'
if = 'has("nvim")'
build = 'npm -g install typescript'

# React JSX syntax highlighting and indenting for vim.
[[plugins]]
repo = 'mxw/vim-jsx'

# Syntax Highligth for Vue.js components
[[plugins]]
repo = 'posva/vim-vue'

# Generate JSDoc to your JavaScript code.
[[plugins]]
repo = 'heavenshell/vim-jsdoc'
on_ft = 'javascript'

# Tools and environment to make Vim superb for developing with Node.js. Like Rails.vim for Node.
[[plugins]]
repo = 'moll/vim-node'
on_ft = 'javascript'

#---------------------------------------------------------------------------
# YAML:
#

# Add additional support for Ansible in VIM
[[plugins]]
repo = 'chase/vim-ansible-yaml'


#---------------------------------------------------------------------------
# Markdown:
#

#---------------------------------------------------------------------------
# Json:
#

# A better JSON for Vim: distinct highlighting of keywords vs values, JSON-specific (non-JS) warnings, quote concealing. Pathogen-friendly.
[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'

#---------------------------------------------------------------------------
# UML:
#

# vim syntax file for plantuml
[[plugins]]
repo = 'aklt/plantuml-syntax'
on_ft = 'plantuml'

# Inline previews for Plantuml sequence diagrams. OMG!
[[plugins]]
repo = 'scrooloose/vim-slumlord'
on_ft = 'plantuml'

#---------------------------------------------------------------------------
# LaTex:
#

# A modern vim plugin for editing LaTeX files.
[[plugins]]
repo = 'lervag/vimtex'
on_ft = ['tex', 'plaintex']
