# Snippet support
[[plugins]]
repo = 'Shougo/neosnippet'
depends = ['neosnippet-snippets']
on_i = 1
on_ft = ['snippet']

# Next generation completion framework
[[plugins]]
repo = 'Shougo/neocomplete'
if = 'has("lua")'
on_i = 1
hook_source = '''
  let g:neocomplete#enable_at_startup = 1
  let g:neocomplete#enable_smart_case = 1
'''

# Dark powered asynchronous completion framework for neovim
[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = 'has("nvim")'
on_i = 1


#---------------------------------------------------------------------------
# Python:
#

# Using the jedi autocompletion library
[[plugins]]
repo = 'davidhalter/jedi-vim'
if = "!has('nvim')"
on_ft = 'python'

# Pyflakes, Pep8 and mccabe code complexity checker
[[plugins]]
repo = "andviro/flake8-vim"
on_ft = 'python'
hook_source = '''
  let g:PyFlakeOnWrite = 1
  let g:PyFlakeCheckers = 'pep8'
'''

# A nicer Python indentation style
[[plugins]]
repo = "hynek/vim-python-pep8-indent"¬
on_ft = 'python'

#---------------------------------------------------------------------------
# HTML5+CSS3:
#

# HTML5 omnicomplete and syntax
[[plugins]]
repo = 'othree/html5.vim'
on_ft = 'html'

# Add CSS3 syntax support
[[plugins]]
repo = 'hail2u/vim-css3-syntax'

#---------------------------------------------------------------------------
# Javascript:
#

# Enhanced javascript syntax file
[[plugins]]
repo = 'jelera/vim-javascript-syntax'
on_ft = 'javascript'
